name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bug'
  - title: '🧰 Maintenance'
    labels: 
      - 'chore'
      - 'refactor'
      - 'style'
  - title: '💻 Code related'
      - 'build'
      - 'ci'
      - 'docs'
      - 'test'
change-template: '- $TITLE #$NUMBER @$AUTHOR'
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
      - 'enhancement'
  patch:
    labels:
      - 'fix'
      - 'bug'
      - 'chore'
      - 'refactor'
      - 'style'
template: |
  ##  What's Changed

  $CHANGES
replacers:
  - search: 'feat: '
    replace: ''
  - search: 'fix: '
    replace: ''
  - search: 'chore: '
    replace: ''
  - search: 'ci: '
    replace: ''
  - search: 'test: '
    replace: ''
  - search: 'refactor: '
    replace: ''
  - search: 'style: '
    replace: ''
  - search: 'build: '
    replace: ''