name: "Pull Request Labeler"
on:
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
  issues:
    types: [opened, edited]
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
      issues: write
      statuses: write
      checks: write
    runs-on: ubuntu-latest
    steps:
      - uses: fuxingloh/multi-labeler@v4
        with:
          github-token: ${{ secrets.DANGER_BOT }}